#!/bin/bash
## DEVELOPMENT
	source development/i3.sh
	source development/java8.sh
	source development/nginx.sh
	source development/zlib.sh
	source development/nightly.sh
	source development/sublime_text.sh
	source development/atom.sh
	source development/mysql.sh
	source development/php5.sh
	source development/apache2.sh
	source development/node.sh

## MAIN
	source main/curl.sh
	source main/filezilla.sh
	source main/gimp.sh
	source main/git.sh
	source main/gmusic.sh
	source main/gparted.sh
	source main/grive.sh
	source main/inkscape.sh
	source main/nuvola.sh
	source main/restricted_extras.sh
	source main/svn.sh
	source main/terminator.sh
	source main/turpial.sh
	source main/numix_circle.sh
	source main/paper.sh
	source main/unsettings.sh
	source main/gchrome.sh
	source main/clementine.sh
	source main/kvm.sh
	source main/zsh
